  version: '2.2'
  services:
    miko:
      build:
        context: ./
#        dockerfile: Dockerfile
        dockerfile: Dockerfile-build
      image: miko_obraz
      ports:
        - 8081
      networks:
        - net1
#      scale: 3
  networks:
    net1:
#   jakby co, to tutaj jest źródło odnośnie dockera
#      https://thepracticaldeveloper.com/2017/12/11/dockerize-spring-boot/